# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0006_auto_20170830_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='estimated_duration',
        ),
    ]
