# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0008_auto_20170918_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='bundle',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bundles_app.Bundle'),
        ),
    ]
