# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 19:19
from __future__ import unicode_literals

import core_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_app', '0003_auto_20170829_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knows',
            name='exp_level',
            field=models.CharField(choices=[('Junior Developer', 'Junior Developer'), ('Semi-Senior Developer', 'Semi-Senior Developer'), ('Senior Developer', 'Senior Developer')], default='Junior Developer', max_length=30),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_logo',
            field=models.ImageField(upload_to=core_app.models.skill_logo_directory_path),
        ),
        migrations.AlterUniqueTogether(
            name='knows',
            unique_together=set([('user', 'skill')]),
        ),
    ]
