# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('about', models.TextField(max_length=255)),
                ('bundle_extra_fee', models.DecimalField(decimal_places=2, max_digits=4)),
                ('bundle_total_fee', models.DecimalField(decimal_places=2, max_digits=4)),
                ('is_custom', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField(max_length=255)),
                ('visual_aid', models.ImageField(upload_to=b'')),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('bundle', models.ManyToManyField(to='bundles_app.Bundle')),
            ],
        ),
    ]
