# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='bundle',
            new_name='bundles',
        ),
        migrations.AlterField(
            model_name='service',
            name='service_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='service',
            name='visual_aid',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
