# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles_app', '0004_auto_20170922_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
