# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles_app', '0005_auto_20170922_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='about',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
