# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bundles_app', '0007_auto_20171003_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='visual_aid',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
