# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_auto_20170830_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo_profile'),
        ),
    ]
