# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_auto_20170904_1519'),
        ('core_app', '0006_auto_20170903_0727'),
    ]

    operations = [
    ]
