# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_merge_20170905_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='../media/photo_profile/default-user.png', upload_to='photo_profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='about',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
    ]
