# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_auto_20170907_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='client_user',
        ),
        migrations.AlterField(
            model_name='request',
            name='telephone_number',
            field=models.CharField(max_length=15),
        ),
    ]
