# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0003_auto_20170829_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='finish_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
