# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0004_auto_20170829_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screenshot',
            old_name='screenshot',
            new_name='img',
        ),
    ]
