# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0005_auto_20170829_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screenshot',
            options={'ordering': ['date_uploaded']},
        ),
        migrations.AddField(
            model_name='screenshot',
            name='is_preview',
            field=models.BooleanField(default=False),
        ),
    ]
