# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0007_remove_project_estimated_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='current_stage',
            field=models.CharField(blank=True, default='Pre-aprobaci\xf3n.', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
